#
#spring.datasource.url=jdbc:postgresql://dpg-d3ncvoa4d50c73cj5a20-a.oregon-postgres.render.com/dbmanager_jr4n
#spring.datasource.username=dbmanager_jr4n_user
#spring.datasource.password=frhmjIkpfP9Rel4txmwZX3b3FvjkiCHc
#
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.data.jdbc.dialect=postgresql

spring.datasource.url=jdbc:postgresql://ep-ancient-thunder-a1momvaq-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_VhEzQ26TLSZB
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# application.properties
brevo.sender.email=${BREVO_SENDER_EMAIL}
brevo.api.key=${BREVO_API_KEY}
FROM_NAME=MoneyTracker


cron.daily_remainder_email_time=${CRON_DAILY_REMAINDER_EMAIL_TIME: 0 * * * * *}
cron.daily_summary_email_time= ${CRON_DAILY_SUMMARY_EMAIL_TIME: 0 * * * * *}

