spring:
  application:
    name: moneytracker

  # Server Configuration
  profiles:
    active: prod

  # Database Configuration
  datasource:
    url: jdbc:postgresql://dpg-d3ncvoa4d50c73cj5a20-a.oregon-postgres.render.com/dbmanager_jr4n
    username: dbmanager_jr4n_user
    password: frhmjIkpfP9Rel4txmwZX3b3FvjkiCHc
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Email Configuration
#  mail:
#    host: smtp-relay.brevo.com
#    port: 587
#    username: 98e632001@smtp-brevo.com
#    password: T7E6rUfOhxMSKcAs
#    protocol: smtp
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#          connectiontimeout: 10000
#          timeout: 10000
#          writetimeout: 10000


# Server Configuration
server:
  port: 8081
  servlet:
    context-path: /api/v1.0





# Cron Configuration
  cron:
    daily:
      remainder:
        email:
          time:
            ${CRON_DAILY_REMAINDER_EMAIL_TIME:  0 0 9 * * *}  # Daily at 9 AM
      summary:
        email:
          time:
            ${CRON_DAILY_SUMMARY_EMAIL_TIME: 0 0 20 * * *}   # Daily at 8 PM


BREVO:
  API:
    KEY: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
FROM:
  EMAIL:keshavchoudhary550@gmail.com